services:
  vscode:
    build: ./
    container_name: vscode
    hostname: vscode
    environment:
      - PORT=8080
      - TZ=Europe/Lisbon
      - SERVER_DATA_DIR=/home/user/.vscode-server
      - VERBOSE=false
    volumes:
      - "./data:/home/user"
      - "/var/run/docker.sock:/var/run/docker.sock"
    restart: always
    user: "1000:1000"
